# Generated by Django 4.1 on 2024-08-21 21:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_auth_type_user_auth_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e56a6675-a55c-49ee-9731-1702e66d9f3e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e56a6675-a55c-49ee-9731-1702e66d9f3e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
